### ISSUE TITLE
Bug: Errors are raised if a lock branch is not found

### ISSUE THREAD

**Issue by GrantBirki** [github/lock#45]
# Errors are raised if a lock branch is not found

In its current state, this Action throws an error if a lock branch is not found. When originally writing this Action, this made sense to me because if the lock branch is created by this Action, or the parent `github/branch-deploy` Action, then it should also be removed by it right?... Wrong.

There are now many bespoke ways that other workflows can integrate with this Action. There are also alternate workflows within the `github/branch-deploy` Action as well such as the [Unlock on Merge](https://github.com/github/branch-deploy/blob/0b9d28770be00ce7d6132dc1791a5455c2e852e5/docs/unlock-on-merge.md) strategy.

Here is an example of the `github/lock` Action raising an exception in a workflow when a lock branch is not found:

![Image](https://github.com/github/lock/assets/23362539/c7bab1be-b11d-4cf2-9366-aa0c217419fe)

Due to this error being raised, the entire workflow fails. Rather than failing the entire workflow, it should simply be aware of this edge case, and log a warning message when it occurs.

---

Error text:

```text
/home/runner/work/_actions/github/lock/v2.1.4/src/functions/unlock.js:116
      throw new Error(error)
^
Error: HttpError: Reference does not exist - https://docs.github.com/rest/git/refs#delete-a-reference
    at unlock (/home/runner/work/_actions/github/lock/v2.1.4/src/functions/unlock.js:116:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at run (/home/runner/work/_actions/github/lock/v2.1.4/src/main.js:49:1)
Error: Error: HttpError: Reference does not exist - https://docs.github.com/rest/git/refs#delete-a-reference
    at unlock (/home/runner/work/_actions/github/lock/v2.1.4/src/functions/unlock.js:116:1)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at run (/home/runner/work/_actions/github/lock/v2.1.4/src/main.js:49:1)
Error: HttpError: Reference does not exist - https://docs.github.com/rest/git/refs#delete-a-reference
```

**Comment by GrantBirki** [comment]
Good news, it looks like this is already being done, but perhaps the API has changed in a way where this condition is no longer being met. (i.e. octokit raising a custom error class rather than returning status codes, etc)

https://github.com/github/lock/blob/fdcc90adf47eaeecb8bb0aa43f1ad73889a7db2b/src/functions/unlock.js#L92

**Comment by GrantBirki** [comment]
This issue is officially just me thinking out load and looping back on a problem I already fixed else where 🤦

https://github.com/github/branch-deploy/issues/249
